<?php foreach ($this->child as $parent): ?>
    <option value="<?php echo $this->escape($parent->pageTitle); ?>" <?php if ($this->contentPage->parentPage !== null && $this->contentPage->parentPage->getPageTitle() == $parent->pageTitle): ?>selected="selected"<?php endif; ?> ><?php echo $this->wid . ' ' . $this->escape($parent->title); ?></option>
    <?php if ($parent->hasChild()): ?>
        <?php echo $this->partial('contentpage/_elements/child.phtml', array('child' => $parent->getChild(), 'contentPage' => $this->contentPage, 'wid' => $this->wid . '--')); ?>
    <?php endif; ?>
<?php endforeach; ?>