<div class="page_guestbook">
    <div class="page_guestbook_inner">

        <?php if (isset($this->exception_msg)): ?>
            <div class="alert alert-error">
                <h4 class="alert-heading">Ошибка!</h4>
                <?php echo $this->escape($this->exception_msg); ?>
            </div>
        <?php endif; ?>

        <?php if ($this->parentItem != null): ?>
            <ul class="breadcrumb">
                <li><a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'view', 'parent' => ''), $this->linkInfo->getFullUrl('-')); ?>"><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Гостевая книга<?php endif; ?></a> <span class="divider">/</span></li>
                <?php if ($this->parentItem->parent !== null): ?>
                    <?php if ($this->parentItem->parent->parent !== null): ?>
                        <?php echo $this->partial('guest-book/_elements/public_breadcrumb.phtml', array('parentItem' => $this->parentItem->parent->parent, 'linkInfo' => $this->linkInfo)); ?>
                    <?php endif; ?>
                    <li><a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'view', 'parent' => $this->parentItem->parent->id), $this->linkInfo->getFullUrl('-') . '-parent'); ?>"><?php echo $this->escape($this->parentItem->parent->getQuestion()); ?></a> <span class="divider">/</span></li>
                <?php endif; ?>
                <li class="active"><?php echo $this->escape($this->parentItem->question); ?></li>
            </ul>
        <?php endif; ?>

        <h1><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Гостевая книга<?php endif; ?></h1>

        <?php if ($this->isComplite): ?>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Внимание!</strong> Ваша заявка отправлена!
            </div>
            <br/>
        <?php endif; ?>

        <?php if ($this->questionList !== false): ?>
            <ul class="document">
                <?php foreach ($this->questionList as $question): ?>
                    <li>
                        <?php if ($question->isFolder): ?>
                            <img src="/images/icon/folder.png"/>&nbsp;<a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'view', 'parent' => $question->id), $this->linkInfo->getFullUrl('-') . '-parent'); ?>"><?php echo $this->escape($question->question); ?></a>
                        <?php else: ?>
                            <a href="<?php echo $this->url(array('controller' => 'guest-book', 'action' => 'view-question', 'id' => $question->id, 'parent' => $question->parent->id), $this->linkInfo->getFullUrl('-') . '-view-question'); ?>"><?php echo $this->escape($question->question); ?></a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <br/>

        <?php if ($this->parentItem != null): ?>
            <a href="#" class="answer_question" onclick="showQuestionForm();">Задать вопрос</a>
            <br/>

            <div id="questionForm" style="display: none;">
                <?php echo $this->form; ?>
            </div>
        <?php endif; ?>
    </div>
</div>