<div class="content">

    <legend><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Реестр УК<?php endif; ?></legend>

    <?php if (isset($this->exception_msg)): ?>
        <div class="alert alert-error">
            <h4 class="alert-heading">Ошибка!</h4>
            <?php echo $this->escape($this->exception_msg); ?>
        </div>
    <?php endif; ?>

    <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'add', 'link' => $this->escape($this->link))) ?>"><i class="icon-plus"></i>Добавить УК</a><br/><br/>


    <table class="table table-bordered">
        <tr>
            <th>Название</th>
            <th>Город</th>
            <th>ОГРН</th>
            <th>Действия</th>
        </tr>

        <?php if ($this->registerList !== false): ?>
            <?php foreach ($this->registerList as $item): ?>
                <tr>
                    <td><?php echo $this->escape($item->title); ?></td>
                    <td><?php echo $this->escape($item->city->title); ?></td>
                    <td><?php echo $this->escape($item->ogrn); ?></td>
                    <td class="tedit">
                        <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'edit', 'id' => $item->id, 'link' => $this->escape($this->link))); ?>"><i class="icon-pencil"></a>
                        <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'delete', 'id' => $item->id, 'link' => $this->escape($this->link))); ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');"><i class="icon-remove"></i></a>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>

    <div class="clear"></div>
</div>

<div class="sidebar">

    <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'add-city', 'link' => $this->escape($this->link))) ?>"><i class="icon-plus"></i> Добавить город</a><br/><br/>

    <ul class="secand_menu">
        <li>
            <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'index', 'link' => $this->escape($this->link), 'cityId' => '')) ?>">ГОРОДА</a>
            <ul>
                <?php if ($this->cityList !== false): ?>
                    <?php foreach ($this->cityList as $item): ?>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'index', 'cityId' => $item->id, 'link' => $this->escape($this->link))) ?>"><?php echo $this->escape($item->title); ?></a>
                            <span class="edit"><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'edit-city', 'cityId' => $item->id, 'link' => $this->escape($this->link))) ?>"><i class="icon-pencil"></i></a></span>
                            <span class="del"><a href="<?php echo $this->url(array('controller' => 'register', 'action' => 'delete-city', 'cityId' => $item->id, 'link' => $this->escape($this->link))) ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');"><i class="icon-remove"></i></a></span>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>

        </li>
    </ul>

</div>