<legend>Добавить площадку</legend>

<?php if (isset($this->exception_msg)): ?>
    <div class="alert alert-error">
        <h4 class="alert-heading">Ошибка!</h4>
        <?php echo $this->escape($this->exception_msg); ?>
    </div>
<?php endif; ?>

<form class="form-horizontal" action="<?php echo $this->url(array('controller' => 'banner', 'action' => 'addPlace')); ?>" method="post" enctype="multipart/form-data">
    <div class="control-group">
        <label class="control-label">Название</label>

        <div class="controls">
            <input type="text" name="data[title]" value="<?php echo $this->escape($this->place->title); ?>"/>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Ширина</label>

        <div class="controls">
            <input type="text" name="data[width]" value="<?php echo $this->escape($this->place->width); ?>"/>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Высота</label>

        <div class="controls">
            <input type="text" name="data[height]" value="<?php echo $this->escape($this->place->height); ?>"/>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Время между сменой баннеров</label>

        <div class="controls">
            <input type="text" name="data[change_time]" value="<?php echo $this->escape($this->place->changeTime); ?>"/>
            <span class="help-inline hide">Заполните поле</span>
        </div>
    </div>

    <div class="form-actions">
        <input type="submit" class="btn btn-success" value="Сохранить"/>
        <a href="<?php echo $this->url(array('controller' => 'banner', 'action' => 'viewPlace')) ?>" class="btn btn-danger">Отмена</a>
    </div>
</form>