<legend>Размещение баннеров. Площадка <?php echo $this->escape($this->place->title); ?></legend>

<?php if (isset($this->exception_msg)): ?>
    <div class="alert alert-error">
        <h4 class="alert-heading">Ошибка!</h4>
        <?php echo $this->escape($this->exception_msg); ?>
    </div>
<?php endif; ?>

<a href="<?php $this->url(array('controller' => 'banner', 'action' => 'viewPlace')); ?>">Все Площадки</a><br/><br/>

<form class="form-horizontal" action="<?php echo $this->url(array('controller' => 'banner', 'action' => 'placemark', 'idPlace' => $this->place->id)); ?>" method="post" enctype="multipart/form-data">

    <table class="table">
        <tr>
            <th>Баннер</th>
            <th style="width: 90px;">Разместить</th>
            <th></th>
        </tr>

        <?php if ($this->bannerList !== false): ?>
            <?php foreach ($this->bannerList as $banner): ?>
                <tr>
                    <td class="ttovar_title"><?php echo $this->escape($banner->title); ?></td>
                    <td class="ttovar"><input type="checkbox" name="data[<?php echo $this->escape($banner->id); ?>][place]" <?php if (isset($this->placeAcl[$banner->id])): ?>checked="checked"<?php endif; ?> /></td>
                    <td class="ttovar"></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>

    </table>

    <div class="form-actions">
        <input type="submit" class="btn btn-success" value="Сохранить"/>
        <a href="<?php echo $this->url(array('controller' => 'banner', 'action' => 'viewPlace')) ?>" class="btn btn-danger">Отмена</a>
    </div>
</form>