<div class="content_main">
    <div class="n_title">
        <a href="#" title="<?php echo $this->escape($this->document->title); ?>"><?php echo $this->escape($this->document->title); ?></a>
    </div>


    <p><?php echo $this->escape($this->document->shortText); ?></p>

    <?php if ($this->document->file->getName()): ?>
        <br/>
        <a href="/files<?php echo $this->escape($this->document->file->getSubPath()); ?>/<?php echo $this->escape($this->document->file->getName()); ?>" target="_blank">загрузить</a>
    <?php endif; ?>

</div>