<legend><?php if (is_object($this->linkInfo)): ?><?php echo $this->escape($this->linkInfo->title); ?><?php else: ?>Партнеры<?php endif; ?></legend>

<?php if (isset($this->exception_msg)): ?>
    <div class="alert alert-error">
        <h4 class="alert-heading">Ошибка!</h4>
        <?php echo $this->escape($this->exception_msg); ?>
    </div>
<?php endif; ?>

<a href="<?php echo $this->url(array('controller' => 'partners', 'action' => 'add', 'link' => $this->escape($this->link))) ?>"><i class="icon-plus"></i>Добавить партнера</a><br/><br/>


<table class="table table-bordered">
    <tr>
        <th>Логотип</th>
        <th>Название</th>
        <th>Ссылка</th>
        <th>Действия</th>
    </tr>

    <?php if ($this->partnersList !== false): ?>
        <?php foreach ($this->partnersList as $item): ?>
            <tr>
                <td><?php if ($item->file->getName()): ?><img src="/files<?php echo $this->escape($item->file->getSubPath()); ?>/<?php echo $this->escape($item->file->getName()); ?>" /><?php endif; ?></td>
                <td><?php echo $this->escape($item->title); ?></td>
                <td><?php echo $this->escape($item->url); ?></td>
                <td class="tedit">
                    <a href="<?php echo $this->url(array('controller' => 'partners', 'action' => 'edit', 'id' => $item->id, 'link' => $this->escape($this->link))); ?>"><i class="icon-pencil"></a>
                    <a href="<?php echo $this->url(array('controller' => 'partners', 'action' => 'delete', 'id' => $item->id, 'link' => $this->escape($this->link))); ?>" onclick="return confirmDelete('<?php echo $this->escape($item->title); ?>');"><i class="icon-remove"></i></a>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>

<div class="clear"></div>
